name: Build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
#    - name: Build HoloInsight Agent
#      shell: bash
#      run: |
#        export GOOS=linux
#        export GOARCH=amd64
#        ./scripts/gen-git-info.sh
#        ./scripts/build/build-using-go.sh
    - name: pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files

    # https://conventionalcommits.org/
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v2
      with:
        pattern: '(?s)(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:( [^\n\r]+)((\n\n.*)|(\s*))?$'
        flags: 'gm'
        error: 'Must use conventional commits'
        excludeTitle: 'true'
        checkAllCommitMessages: 'true'
        accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
