name: PR merge gate

on:
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  pr-merge-gate:
    runs-on: ubuntu-latest
    #if: (github.repository == 'traas-stack/holoinsight-agent')
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    - name: Build HoloInsight Agent
      shell: bash
      run: |
        export GOOS=linux
        export GOARCH=amd64
        ./scripts/gen-git-info.sh
        ./scripts/build/build-using-go.sh
    - name: pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files

    # https://conventionalcommits.org/
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v2
      with:
        pattern: '(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)'
        flags: 'gm'
        error: 'Must use conventional commits'
        excludeTitle: 'true'
        checkAllCommitMessages: 'true'
        accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
