name: Upload release docker image

on:
  release:
    types: [ published ]

concurrency:
  group: holoinsight-agent-upload-release-docker-image-${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  upload-release-docker-image:
    runs-on: ubuntu-latest
    if: startsWith( github.event.release.tag_bname, "v" )
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Upload HoloInsight Agent Docker Image
      shell: bash
      run: |
        docker buildx create --use
        ./scripts/gen-git-info.sh
        tag=${GITHUB_REF_NAME:1} ./scripts/docker/buildx.sh
